name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate to Google
      id: 'auth'
      uses: google-github-actions/auth@v0.7.0
      with:
        token_format: 'id_token'
        workload_identity_provider: 'projects/maginobi-webapps/locations/global/workloadIdentityPools/maginobi-webapps-github/providers/github'
        service_account: 'github-service-acct@maginobi-webapps.iam.gserviceaccount.com'
        id_token_audience: 'https://iam.googleapis.com/projects/1078883167077/locations/global/workloadIdentityPools/maginobi-webapps-github/providers/github'
        create_credentials_file: true
    - name: Login with gcloud
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag us-central1-docker.pkg.dev/maginobi-webapps/warpgate-translator/warpgate-translator:$(date +%s)
    - name: Push the Docker image
      run: docker push us-central1-docker.pkg.dev/maginobi-webapps/warpgate-translator/warpgate-translator:$(date +%s)
