name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  WORKLOAD_IDENTITY_POOL_PROVIDER: 'projects/1078883167077/locations/global/workloadIdentityPools/maginobi-webapps-github/providers/github'
  SERVICE_ACCOUNT: 'github-service-acct@maginobi-webapps.iam.gserviceaccount.com'

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Set image tag
      run: echo "IMAGE_TAG=us-central1-docker.pkg.dev/maginobi-webapps/warpgate-translator/warpgate-translator:$(date +%s)" >> $GITHUB_ENV
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate to Google
      id: 'auth'
      uses: google-github-actions/auth@v0.7.0
      with:
        token_format: 'id_token'
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}
        id_token_audience: ${{ env.WORKLOAD_IDENTITY_POOL_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        create_credentials_file: true
    - name: Login with gcloud
      run: |
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}
